class CreateAuthentications < ActiveRecord::Migration[5.2]
  def change
    create_table :authentications do |t|
      t.string :uid # this is a string generated by the provider that uniquely identifies a user
      t.string :token # this will take the form of a string and is an access token. It is generated by the provider after successful authentication by the provider of our app, and approved authorization by the user (note that we need not store this unless we want to perform various actions on the user's behalf - for example - fetch friends' information, post a status on our behalf, etc).
      t.string :provider # the authorization provider. Also a string.
      t.references :user, foreign_key: true # this user ID refers to the ID of the user stored in our app's database.

      t.timestamps
    end
  end
end
